apiVersion: v1
kind: Service
metadata:
  name: alphabet-checker-api-service
spec:
  type: LoadBalancer
  selector:
    app: alphabet-checker-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
